/**
 * Demo/mock data for UI development without a database connection.
 * Activated when demo mode is enabled via environment configuration.
 */

import { isDemoModeEnabled } from '../config/env';

export const DEMO_MODE = isDemoModeEnabled();

export const demoEvents = [
  {
    id: 'evt-001',
    name: 'Aurrin Demo Day — March 2026',
    description: 'Monthly pitch night for Calgary early-stage founders. Microgrants awarded to top pitches.',
    status: 'live' as const,
    start_date: '2026-03-28T18:00:00.000Z',
    end_date: '2026-03-28T22:00:00.000Z',
    scoring_start: '2026-03-28T18:00:00.000Z',
    scoring_end: '2026-03-29T18:00:00.000Z',
    publishing_start: '2026-03-30T09:00:00.000Z',
    publishing_end: '2026-04-07T18:00:00.000Z',
    max_judges: 5,
    max_founders: 8,
    rubric_id: 'rubric-001',
    judges_count: 4,
    founders_count: 6,
    created_at: '2026-03-01T00:00:00.000Z',
    updated_at: '2026-03-20T00:00:00.000Z',
  },
  {
    id: 'evt-002',
    name: 'Aurrin Demo Day — February 2026',
    description: 'February pitch night. Theme: Climate & Sustainability.',
    status: 'archived' as const,
    start_date: '2026-02-21T18:00:00.000Z',
    end_date: '2026-02-21T22:00:00.000Z',
    scoring_start: '2026-02-21T18:00:00.000Z',
    scoring_end: '2026-02-22T18:00:00.000Z',
    publishing_start: '2026-02-23T09:00:00.000Z',
    publishing_end: '2026-03-03T18:00:00.000Z',
    max_judges: 5,
    max_founders: 8,
    rubric_id: 'rubric-001',
    judges_count: 5,
    founders_count: 8,
    created_at: '2026-02-01T00:00:00.000Z',
    updated_at: '2026-02-25T00:00:00.000Z',
  },
  {
    id: 'evt-003',
    name: 'Aurrin Demo Day — April 2026',
    description: 'Upcoming pitch night. Theme: AI & Automation.',
    status: 'upcoming' as const,
    start_date: '2026-04-25T18:00:00.000Z',
    end_date: '2026-04-25T22:00:00.000Z',
    scoring_start: '2026-04-25T18:00:00.000Z',
    scoring_end: '2026-04-26T18:00:00.000Z',
    publishing_start: '2026-04-27T09:00:00.000Z',
    publishing_end: '2026-05-05T18:00:00.000Z',
    max_judges: 5,
    max_founders: 10,
    rubric_id: 'rubric-001',
    judges_count: 2,
    founders_count: 3,
    created_at: '2026-03-15T00:00:00.000Z',
    updated_at: '2026-03-15T00:00:00.000Z',
  },
];

export const demoDirectoryProfiles = [
  {
    founder_slug: 'maya-chen-terravolt',
    founder_name: 'Maya Chen',
    company: 'TerraVolt Energy',
    industry: 'CleanTech',
    stage: 'Seed',
    summary: 'Building modular battery storage for off-grid communities in Northern Alberta. Deployed 3 pilot units serving 120 households.',
    photo: null,
    score: 87,
    event: { id: 'evt-002', name: 'Aurrin Demo Day — February 2026' },
  },
  {
    founder_slug: 'jordan-okafor-freightmind',
    founder_name: 'Jordan Okafor',
    company: 'FreightMind',
    industry: 'Logistics',
    stage: 'Pre-Seed',
    summary: 'AI-powered load matching for independent truckers across Western Canada. $40K MRR, 200+ active carriers.',
    photo: null,
    score: 82,
    event: { id: 'evt-002', name: 'Aurrin Demo Day — February 2026' },
  },
  {
    founder_slug: 'priya-sharma-rootwise',
    founder_name: 'Priya Sharma',
    company: 'RootWise',
    industry: 'AgTech',
    stage: 'Seed',
    summary: 'Soil health analytics platform using satellite imagery and ground sensors. Partnered with 15 farms across southern Alberta.',
    photo: null,
    score: 79,
    event: { id: 'evt-001', name: 'Aurrin Demo Day — March 2026' },
  },
  {
    founder_slug: 'liam-blackwood-civicpulse',
    founder_name: 'Liam Blackwood',
    company: 'CivicPulse',
    industry: 'GovTech',
    stage: 'Pre-Seed',
    summary: 'Resident engagement platform for municipal governments. Pilot with City of Lethbridge, 3 more municipalities in pipeline.',
    photo: null,
    score: 76,
    event: { id: 'evt-001', name: 'Aurrin Demo Day — March 2026' },
  },
  {
    founder_slug: 'amara-diallo-nourish',
    founder_name: 'Amara Diallo',
    company: 'Nourish Collective',
    industry: 'FoodTech',
    stage: 'Idea',
    summary: 'Community-owned dark kitchen network connecting immigrant chefs to local demand. Validated with 50 pre-orders in one weekend.',
    photo: null,
    score: 73,
    event: { id: 'evt-001', name: 'Aurrin Demo Day — March 2026' },
  },
  {
    founder_slug: 'ethan-wolfe-trailstack',
    founder_name: 'Ethan Wolfe',
    company: 'TrailStack',
    industry: 'EdTech',
    stage: 'Pre-Seed',
    summary: 'Micro-credentialing platform for trades apprenticeships. Integrates with Alberta apprenticeship board standards.',
    photo: null,
    score: 71,
    event: { id: 'evt-002', name: 'Aurrin Demo Day — February 2026' },
  },
  {
    founder_slug: 'sofia-reyes-petravr',
    founder_name: 'Sofia Reyes',
    company: 'PetraVR',
    industry: 'HealthTech',
    stage: 'Seed',
    summary: 'VR-based physiotherapy for post-surgical rehab. Clinical trial partnership with Foothills Medical Centre.',
    photo: null,
    score: 68,
    event: { id: 'evt-002', name: 'Aurrin Demo Day — February 2026' },
  },
  {
    founder_slug: 'kai-nakamura-loopbox',
    founder_name: 'Kai Nakamura',
    company: 'LoopBox',
    industry: 'CleanTech',
    stage: 'Idea',
    summary: 'Reusable packaging-as-a-service for Calgary restaurants. Reduces single-use waste with deposit-return smart containers.',
    photo: null,
    score: 65,
    event: { id: 'evt-001', name: 'Aurrin Demo Day — March 2026' },
  },
];

export const demoSponsors = [
  {
    id: 'sponsor-001',
    name: 'Calgary Economic Development',
    logo: null,
    link: 'https://calgaryeconomicdevelopment.com',
    tier: 'gold' as const,
    scope: 'site-wide',
    event_id: null,
    status: 'active',
  },
  {
    id: 'sponsor-002',
    name: 'ATB Financial',
    logo: null,
    link: 'https://atb.com',
    tier: 'gold' as const,
    scope: 'site-wide',
    event_id: null,
    status: 'active',
  },
  {
    id: 'sponsor-003',
    name: 'Platform Calgary',
    logo: null,
    link: 'https://platformcalgary.com',
    tier: 'silver' as const,
    scope: 'event',
    event_id: 'evt-001',
    status: 'active',
  },
  {
    id: 'sponsor-004',
    name: 'Thin Air Labs',
    logo: null,
    link: 'https://thinairlabs.com',
    tier: 'bronze' as const,
    scope: 'event',
    event_id: 'evt-001',
    status: 'active',
  },
];

export const demoFounderApplications = [
  {
    id: 'app-001',
    email: 'maya@terravolt.ca',
    name: 'Maya Chen',
    full_name: 'Maya Chen',
    company_name: 'TerraVolt Energy',
    pitch_summary: 'Modular battery storage for off-grid communities.',
    industry: 'CleanTech',
    stage: 'Seed',
    status: 'accepted' as const,
    assigned_event_id: 'evt-002',
    created_at: '2026-02-05T00:00:00.000Z',
    updated_at: '2026-02-08T00:00:00.000Z',
  },
  {
    id: 'app-002',
    email: 'jordan@freightmind.io',
    name: 'Jordan Okafor',
    full_name: 'Jordan Okafor',
    company_name: 'FreightMind',
    pitch_summary: 'AI load matching for independent truckers.',
    industry: 'Logistics',
    stage: 'Pre-Seed',
    status: 'assigned' as const,
    assigned_event_id: 'evt-001',
    created_at: '2026-03-01T00:00:00.000Z',
    updated_at: '2026-03-05T00:00:00.000Z',
  },
  {
    id: 'app-003',
    email: 'priya@rootwise.ag',
    name: 'Priya Sharma',
    full_name: 'Priya Sharma',
    company_name: 'RootWise',
    pitch_summary: 'Soil health analytics using satellite imagery.',
    industry: 'AgTech',
    stage: 'Seed',
    status: 'assigned' as const,
    assigned_event_id: 'evt-001',
    created_at: '2026-03-02T00:00:00.000Z',
    updated_at: '2026-03-06T00:00:00.000Z',
  },
  {
    id: 'app-004',
    email: 'newfounder@example.com',
    name: 'Alex Rivera',
    full_name: 'Alex Rivera',
    company_name: 'UrbanNest',
    pitch_summary: 'Smart co-living platform for remote workers relocating to Calgary.',
    industry: 'PropTech',
    stage: 'Idea',
    status: 'pending' as const,
    assigned_event_id: null,
    created_at: '2026-03-25T00:00:00.000Z',
    updated_at: '2026-03-25T00:00:00.000Z',
  },
  {
    id: 'app-005',
    email: 'declined@example.com',
    name: 'Sam Torres',
    full_name: 'Sam Torres',
    company_name: 'QuickShip YYC',
    pitch_summary: 'Same-day local delivery aggregator.',
    industry: 'Logistics',
    stage: 'Idea',
    status: 'declined' as const,
    assigned_event_id: null,
    created_at: '2026-02-20T00:00:00.000Z',
    updated_at: '2026-02-22T00:00:00.000Z',
  },
];

export const demoFounderProfile = {
  id: 'user-founder-001',
  email: 'maya@terravolt.ca',
  name: 'Maya Chen',
  company: 'TerraVolt Energy',
  industry: 'CleanTech',
  stage: 'Seed',
  website: 'https://terravolt.ca',
  twitter: '@terravolt_ca',
  linkedin: 'https://linkedin.com/in/mayachen',
  bio: 'Energy engineer turned founder. Building affordable off-grid power storage for northern communities.',
  pitches: [
    {
      id: 'pitch-001',
      event_id: 'evt-002',
      event_name: 'Aurrin Demo Day — February 2026',
      score: 87,
      rank: 1,
      status: 'published',
    },
    {
      id: 'pitch-002',
      event_id: 'evt-001',
      event_name: 'Aurrin Demo Day — March 2026',
      score: null,
      rank: null,
      status: 'assigned',
    },
  ],
  reports: [
    {
      id: 'report-001',
      event_name: 'Aurrin Demo Day — February 2026',
      generated_at: '2026-02-25T00:00:00.000Z',
      type: 'score_breakdown',
    },
  ],
};

export const demoJudgeEvents = [
  {
    id: 'evt-001',
    name: 'Aurrin Demo Day — March 2026',
    status: 'live',
    date: '2026-03-28T18:00:00.000Z',
    pitches_to_score: 6,
    scored: 2,
    remaining: 4,
  },
  {
    id: 'evt-002',
    name: 'Aurrin Demo Day — February 2026',
    status: 'archived',
    date: '2026-02-21T18:00:00.000Z',
    pitches_to_score: 8,
    scored: 8,
    remaining: 0,
  },
];

export const demoMentorMatches = [
  {
    id: 'match-001',
    founder_name: 'Maya Chen',
    founder_company: 'TerraVolt Energy',
    industry: 'CleanTech',
    status: 'accepted',
    matched_at: '2026-03-01T00:00:00.000Z',
    intro_sent: true,
  },
  {
    id: 'match-002',
    founder_name: 'Priya Sharma',
    founder_company: 'RootWise',
    industry: 'AgTech',
    status: 'pending',
    matched_at: '2026-03-20T00:00:00.000Z',
    intro_sent: false,
  },
];

export const demoSubscriptions = [
  {
    id: 'sub-001',
    plan: 'Aurrin Pro',
    status: 'active',
    interval: 'monthly',
    amount_cents: 2900,
    current_period_end: '2026-04-27T00:00:00.000Z',
  },
];

export const demoProducts = [
  {
    id: 'prod-001',
    name: 'Aurrin Pro Subscription',
    description: 'Premium access to founder reports, analytics, and directory features.',
    type: 'subscription',
    price_cents: 2900,
    interval: 'monthly',
    active: true,
  },
  {
    id: 'prod-002',
    name: 'Calgary Startup Ecosystem Map 2026',
    description: 'Comprehensive map of Calgary startups, investors, and resources.',
    type: 'digital',
    price_cents: 4900,
    interval: null,
    active: true,
  },
  {
    id: 'prod-003',
    name: 'Founder Scorecard — February 2026',
    description: 'Detailed scoring data and validation insights from February Demo Day.',
    type: 'digital',
    price_cents: 1900,
    interval: null,
    active: true,
  },
];

export const demoAnalytics = {
  total_events: 12,
  total_founders: 47,
  total_pitches: 62,
  total_judges: 18,
  total_audience_sessions: 340,
  total_revenue_cents: 287400,
  active_subscribers: 23,
  avg_score: 74.2,
};
